# Generated by Django 3.2.8 on 2021-11-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.IntegerField(default=-1)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=1000)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=30)),
                ('num_files', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='STUDENT', max_length=15)),
                ('cohorts', models.ManyToManyField(to='hypeapi.Cohort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypeapi.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypeapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_type', models.CharField(default='', max_length=20)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypeapi.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('end_time', models.TimeField()),
                ('link', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='hypeapi.cohort')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='cohorts',
            field=models.ManyToManyField(to='hypeapi.Cohort'),
        ),
    ]
